spring:
  application:
    name: ai_agent
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma4:e2b
    mcp:
      client:
        streamable-http:
          connections:
            score-service:
              url: http://localhost:8090
              endpoint: /mcp
    chat:
      observations:
        include-prompt: true
        include-completion: true

management:
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    resource-attributes:
      service.name: "ai_agent"
    tracing:
      export:
        otlp:
          endpoint: "http://localhost:3000/api/public/otel/v1/traces"
          transport: "http"
          headers:
            Authorization: "Basic <BASE64(pk-lf-...:sk-lf-...)>"
  observations:
    http:
      server:
        requests:
          enabled: false
      client:
        requests:
          enabled: false

logging:
  level:
    root: INFO
    com.example.ai_agent: DEBUG