spring:
  application:
    name: ai_agent
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma4:e2b
    mcp:
      client:
        streamable-http:
          connections:
            score-service:
              url: http://localhost:8090
              endpoint: /mcp
    chat:
      observations:
        include-prompt: true       # Sends prompts as trace tags
        include-completion: true   # Sends responses as trace tag

management:
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: "http://localhost:3000/api/public/otel"
          transport: "http"
          headers:
            Authorization: "Bearer cGstbGYtZDRmMmVlM2ItYTg0Ni00ODc4LWEyNjktMzI4ZGE1MjBkYTkyOnNrLWxmLTRiNzQwMTBlLTFmYjMtNDhiMy1iNzIyLTVkMmU5YmQxYWQ2ZA=="

logging:
  level:
    root: DEBUG